### ISSUE TITLE
New guava code

### ISSUE THREAD

**Issue by skinkie** [rutebanken/netex-java-model#1]
At this moment something in this code generates code with Guava Objects.toStringHelper(). Since this function is deprecated and I don't know where I can force the generation of the new Guava code I hope someone can assist. I have found that the new method would be MoreObjects.toStringHelper()

 https://github.com/seanlandsman/guavagenerators/issues/4

**Comment by csolem** [comment]
Seems like the plugin we use does not support the new Guava MoreObjects. More information here:
https://github.com/danielwegener/xjc-guava-plugin/pull/8
https://github.com/danielwegener/xjc-guava-plugin/issues/4

**Comment by csolem** [comment]
References to the deprecated Guava `Objects.toStringHelper` is now removed. Because the xjc plugin for guava tostring is not updated to use MoreObject, we are now using the xjc plugin: `cxf-xjc-ts` with a custom ToStringStyle.

**Comment by skinkie** [comment]
@csolem thanks for the quick follow up :-)
